version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn --pure-lockfile
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn test
      - run: bash <(curl -s https://codecov.io/bash)


